"""Build the consolidated daily SJ - LINE voucher from Daily Production Reports.

One voucher per (company, report_date) covers all shifts and lines that ran
that day. Each model contributes:
  - Source: BLANK GLASS - <model> @ 6A - MAIN STORES, qty = cum input
  - Dest:   DRILLED GLASS - <model> @ 6A - MAIN STORES, qty = cum input - cum rejection

Plus two aggregate scrap items at SCRAP GODOWN, computed from per-model
physical specs:
  - PLAIN GLASS SCRAP CLEAR (Kgs): full-sheet weight × pieces rejected anywhere
    on the line up to and including drilling output (no cullet credit).
  - CIRCLE CULLET SCRAP CLEAR (Kgs): hole-cullet weight × good drilled pieces.
"""

from __future__ import annotations

import math
from dataclasses import dataclass, field

from sqlalchemy import select
from sqlalchemy.orm import Session

from .models import (
    DailyProductionReport,
    DPRHourlyCell,
    DPRHourModel,
    ProductionModelSpec,
    ProductionProcess,
    StockGroup,
    StockItem,
)


_BLANK_GLASS_PREFIX = "BLANK GLASS - "
_DRILLED_GLASS_PREFIX = "DRILLED GLASS - "


def _tally_company_for_master_lookup() -> str:
    """Tally company whose master tables we cross-check against. See
    ``webapp.main._tally_company_name`` — kept duplicated here so this module
    has no webapp dependency."""
    import os
    return (os.getenv("TALLY_COMPANY_NAME") or "Avinash Appliances Private Limited (April 26 - March 27)").strip()


def model_stock_presence(session: Session) -> tuple[set[str], set[str]]:
    """Return ``(blank_models, drilled_models)`` — uppercase model names found
    in Tally's ``BLANK GLASS - <model>`` and ``DRILLED GLASS - <model>`` stock
    items respectively, under ``TALLY_COMPANY_NAME``."""
    company = _tally_company_for_master_lookup()
    if not company:
        return set(), set()
    rows = session.scalars(
        select(StockItem.name).where(StockItem.company_name == company)
    )
    blank_pl = _BLANK_GLASS_PREFIX.lower()
    drilled_pl = _DRILLED_GLASS_PREFIX.lower()
    blank: set[str] = set()
    drilled: set[str] = set()
    for name in rows:
        if not name:
            continue
        s = str(name).strip()
        low = s.lower()
        if low.startswith(blank_pl):
            tail = s[len(_BLANK_GLASS_PREFIX):].strip().upper()
            if tail:
                blank.add(tail)
        elif low.startswith(drilled_pl):
            tail = s[len(_DRILLED_GLASS_PREFIX):].strip().upper()
            if tail:
                drilled.add(tail)
    return blank, drilled


GLASS_DENSITY_G_PER_CC = 2.5
SOURCE_GODOWN = "6A - MAIN STORES"
DEST_GODOWN = "6A - MAIN STORES"
SCRAP_GODOWN = "SCRAP GODOWN"
VOUCHER_TYPE = "SJ - LINE"
PLAIN_SCRAP_ITEM = "PLAIN GLASS SCRAP CLEAR (Kgs)"
CIRCLE_SCRAP_ITEM = "CIRCLE CULLET SCRAP CLEAR (Kgs)"
DEFAULT_SCRAP_RATE = 5.50


def weight_per_blank_kg(spec: ProductionModelSpec) -> float:
    """Mass of one full BLANK sheet in kg. Hardcoded glass density 2.5 g/cc."""
    return spec.length_mm * spec.width_mm * spec.thickness_mm * GLASS_DENSITY_G_PER_CC * 1e-6


def cullet_per_drilled_kg(spec: ProductionModelSpec) -> float:
    """Mass of cullet generated by drilling one piece, in kg.

    Sums over the model's hole rows: each diameter contributes
    π·(d/2)² × thickness × density × count. A model with no holes returns 0."""
    total = 0.0
    for hole in spec.holes:
        if hole.diameter_mm <= 0 or hole.count <= 0:
            continue
        radius = hole.diameter_mm / 2.0
        total += math.pi * radius * radius * spec.thickness_mm * hole.count
    return total * GLASS_DENSITY_G_PER_CC * 1e-6


@dataclass
class ModelDayTotals:
    model: str
    input_qty: float = 0.0
    rejection_qty: float = 0.0
    contributing_reports: list[int] = field(default_factory=list)

    @property
    def drilled_qty(self) -> float:
        return self.input_qty - self.rejection_qty


def _resolve_hour_chain(
    primary: str, hour_models: dict[str, str], hour_keys: list[str]
) -> dict[str, str]:
    """Walk hours left→right; each override propagates forward until the next change."""
    chain: dict[str, str] = {}
    current = (primary or "").strip()
    for k in hour_keys:
        override = (hour_models.get(k) or "").strip()
        if override:
            current = override
        chain[k] = current
    return chain


def aggregate_day(
    session: Session, company: str, report_date: str
) -> dict[str, ModelDayTotals]:
    """Return {model: ModelDayTotals} aggregated across every DPR that day."""
    reports = list(session.scalars(
        select(DailyProductionReport).where(
            DailyProductionReport.company_name == company,
            DailyProductionReport.report_date == report_date,
        )
    ))
    out: dict[str, ModelDayTotals] = {}
    for report in reports:
        _accumulate_report(session, report, out)
    return out


def _accumulate_report(
    session: Session, report: DailyProductionReport, out: dict[str, ModelDayTotals]
) -> None:
    # Hour ordering — derive from the cells actually persisted on this report
    # plus the report's hour_slots_json. We only need to know *which* hour_keys
    # exist; rejection cells without a recognized hour fall through to the
    # report's primary model.
    import json
    hour_keys: list[str] = []
    if report.hour_slots_json:
        try:
            slots = json.loads(report.hour_slots_json)
            hour_keys = [s.get("key") for s in slots if s.get("key")]
        except (ValueError, AttributeError):
            hour_keys = []
    if not hour_keys:
        # Fallback: collect distinct non-cumulative hour keys from cells.
        hour_keys = sorted({
            c.hour_key for c in report.cells if c.hour_key and c.hour_key != "cumulative"
        })

    hour_model_overrides = {hm.hour_key: hm.model for hm in report.hour_models if hm.model}
    chain = _resolve_hour_chain(report.model, hour_model_overrides, hour_keys)

    # Load process catalog for this report's line so we know which row_keys
    # are 'input' production rows vs rejection rows.
    procs = list(session.scalars(
        select(ProductionProcess).where(
            ProductionProcess.company_name == report.company_name,
            ProductionProcess.line == report.line,
        )
    ))
    input_row_keys = {str(p.id) for p in procs if p.section == "production" and p.role == "input"}
    rejection_row_keys = {str(p.id) for p in procs if p.section == "rejection"}

    for cell in report.cells:
        if cell.hour_key == "cumulative":
            continue  # avoid double counting; cumulative is sum of hourlies
        model = chain.get(cell.hour_key) or (report.model or "").strip()
        if not model:
            continue
        bucket = out.setdefault(model, ModelDayTotals(model=model))
        if report.id not in bucket.contributing_reports:
            bucket.contributing_reports.append(report.id)
        if cell.section == "production" and cell.row_key in input_row_keys:
            bucket.input_qty += cell.value or 0.0
        elif cell.section == "rejection" and cell.row_key in rejection_row_keys:
            bucket.rejection_qty += cell.value or 0.0


@dataclass
class VoucherBuildResult:
    voucher: dict
    missing_specs: list[str]
    plain_scrap_kg: float
    circle_scrap_kg: float
    per_model: list[ModelDayTotals]
    narration_detail: str = ""
    skipped_missing_stock: list[dict] = field(default_factory=list)
    # Each entry: {"model": str, "missing": "blank" | "drilled" | "both"}


def build_sj_line_voucher(
    session: Session,
    company: str,
    report_date: str,
    *,
    scrap_rate: float = DEFAULT_SCRAP_RATE,
    remote_id: str | None = None,
) -> VoucherBuildResult:
    """Assemble the voucher dict expected by TallyClient.import_voucher.

    Models without a ProductionModelSpec are listed in ``missing_specs`` and
    are excluded from scrap calculations (their input/output piece rows are
    still emitted so the voucher reflects the day's piece-level reality)."""
    per_model_map = aggregate_day(session, company, report_date)
    # Stable ordering: alphabetical model name.
    per_model = [per_model_map[m] for m in sorted(per_model_map)]

    # Specs are looked up by model name globally — a model belongs to one
    # OEM customer (BUTTERFLY, SRHA, etc.) which is independent of the
    # Tally company filing this voucher, so don't filter by ``company``.
    from sqlalchemy.orm import selectinload
    specs = {
        s.model: s for s in session.scalars(
            select(ProductionModelSpec)
            .options(selectinload(ProductionModelSpec.holes))
        )
    }

    inventory: list[dict] = []
    plain_scrap_kg = 0.0
    circle_scrap_kg = 0.0
    missing: list[str] = []
    blank_set, drilled_set = model_stock_presence(session)
    skipped_missing: list[dict] = []
    skipped_models: set[str] = set()

    for totals in per_model:
        if totals.input_qty <= 0 and totals.drilled_qty <= 0:
            continue
        key = (totals.model or "").strip().upper()
        has_b = key in blank_set
        has_d = key in drilled_set
        if not (has_b and has_d):
            # Either BLANK GLASS - <model> or DRILLED GLASS - <model> (or both)
            # is absent in Tally — posting would fail or auto-create empty
            # items, so skip and surface for the UI.
            if not has_b and not has_d:
                miss = "both"
            elif not has_b:
                miss = "blank"
            else:
                miss = "drilled"
            skipped_missing.append({"model": totals.model, "missing": miss})
            skipped_models.add(totals.model)
            continue
        spec = specs.get(totals.model)
        blank_price = float(spec.blank_price) if spec and spec.blank_price else None
        drilled_price = float(spec.drilled_price) if spec and spec.drilled_price else None
        # Source (consume) — BLANK
        blank_entry: dict = {
            "item_name": f"BLANK GLASS - {totals.model}",
            "quantity": round(totals.input_qty, 3),
            "uom": "No.",
            "godown": SOURCE_GODOWN,
            "direction": "out",
        }
        if blank_price is not None:
            blank_entry["rate"] = blank_price
            blank_entry["amount"] = round(totals.input_qty * blank_price, 2)
        inventory.append(blank_entry)
        # Destination (produce) — DRILLED
        drilled_entry: dict = {
            "item_name": f"DRILLED GLASS - {totals.model}",
            "quantity": round(totals.drilled_qty, 3),
            "uom": "No.",
            "godown": DEST_GODOWN,
            "direction": "in",
        }
        if drilled_price is not None:
            drilled_entry["rate"] = drilled_price
            drilled_entry["amount"] = round(totals.drilled_qty * drilled_price, 2)
        inventory.append(drilled_entry)
        spec = specs.get(totals.model)
        if spec is None:
            missing.append(totals.model)
            continue
        plain_scrap_kg += weight_per_blank_kg(spec) * max(totals.rejection_qty, 0.0)
        circle_scrap_kg += cullet_per_drilled_kg(spec) * max(totals.drilled_qty, 0.0)

    plain_scrap_kg = round(plain_scrap_kg, 2)
    circle_scrap_kg = round(circle_scrap_kg, 2)

    if plain_scrap_kg > 0:
        inventory.append({
            "item_name": PLAIN_SCRAP_ITEM,
            "quantity": plain_scrap_kg,
            "uom": "Kg",
            "godown": SCRAP_GODOWN,
            "rate": scrap_rate,
            "amount": round(plain_scrap_kg * scrap_rate, 2),
            "direction": "in",
        })
    if circle_scrap_kg > 0:
        inventory.append({
            "item_name": CIRCLE_SCRAP_ITEM,
            "quantity": circle_scrap_kg,
            "uom": "Kg",
            "godown": SCRAP_GODOWN,
            "rate": scrap_rate,
            "amount": round(circle_scrap_kg * scrap_rate, 2),
            "direction": "in",
        })

    # Detailed multi-line narration for the on-screen preview only — Tally's
    # voucher view shows the narration as a single squished line, so the long
    # form is unreadable there.
    detail_lines = [
        f"SJ - LINE consolidated for {report_date} ({len(per_model)} model(s)).",
        "",
        "Per-model breakdown (Input - Rejection = Drilled):",
    ]
    if skipped_missing:
        parts = [f"{e['model']} ({e['missing']} missing)" for e in skipped_missing]
        detail_lines.append(
            f"Skipped {len(skipped_missing)} model(s) — BLANK / DRILLED stock item not found in Tally: "
            + ", ".join(sorted(parts))
        )
    for t in per_model:
        if t.model in skipped_models:
            continue
        spec = specs.get(t.model)
        if spec is None:
            detail_lines.append(
                f"  {t.model}: in {t.input_qty:g} - rej {t.rejection_qty:g} = drilled {t.drilled_qty:g}; spec missing, no scrap"
            )
            continue
        wpb = weight_per_blank_kg(spec)
        cpd = cullet_per_drilled_kg(spec)
        plain = wpb * max(t.rejection_qty, 0.0)
        cullet = cpd * max(t.drilled_qty, 0.0)
        hole_desc = ", ".join(
            f"{h.count}×Ø{h.diameter_mm:g}" for h in sorted(spec.holes, key=lambda h: -h.diameter_mm)
        ) or "no holes"
        detail_lines.append(
            f"  {t.model} ({spec.length_mm:g}x{spec.width_mm:g}x{spec.thickness_mm:g}mm, {hole_desc}): "
            f"in {t.input_qty:g} - rej {t.rejection_qty:g} = drilled {t.drilled_qty:g}; "
            f"plain {wpb:.3f}kg/blank x {t.rejection_qty:g} = {plain:.2f}kg; "
            f"cullet {cpd:.4f}kg/pc x {t.drilled_qty:g} = {cullet:.2f}kg"
        )
    detail_lines.append("")
    detail_lines.append(
        f"Total scrap: PLAIN {plain_scrap_kg:.2f}kg + CULLET {circle_scrap_kg:.2f}kg @ Rs.{scrap_rate:g}/kg "
        f"(density 2.5 g/cc, formulas L*W*T*2.5e-6 and pi*r^2*T*count*2.5e-6)."
    )
    narration_detail = "\n".join(detail_lines)

    # Compact narration for Tally — one short summary line per model, then
    # totals. Tally's narration band can comfortably show this without the
    # text running off-screen.
    model_summaries = []
    total_input = 0.0
    total_drilled = 0.0
    for t in per_model:
        if t.model in skipped_models:
            continue
        total_input += t.input_qty
        total_drilled += t.drilled_qty
        model_summaries.append(
            f"{t.model} {t.input_qty:g}->{t.drilled_qty:g} (rej {t.rejection_qty:g})"
        )
    short_lines = [f"SJ-LINE {report_date} | {len(model_summaries)} model(s)"]
    short_lines.extend(model_summaries)
    short_lines.append(
        f"Totals: input {total_input:g}, drilled {total_drilled:g}, "
        f"scrap PLAIN {plain_scrap_kg:.2f}kg + CULLET {circle_scrap_kg:.2f}kg @ Rs.{scrap_rate:g}/kg"
    )
    if skipped_missing:
        skip_parts = sorted(f"{e['model']} ({e['missing']})" for e in skipped_missing)
        short_lines.append(f"Skipped: {', '.join(skip_parts)}")
    narration_short = "\n".join(short_lines)

    voucher = {
        "voucher_type": VOUCHER_TYPE,
        "date": report_date,
        "narration": narration_short,
        "remote_id": remote_id or f"sjline-{company}-{report_date}".replace(" ", "_"),
        "inventory_entries": inventory,
        "objview": "Consumption Voucher View",
    }
    return VoucherBuildResult(
        voucher=voucher,
        missing_specs=missing,
        plain_scrap_kg=plain_scrap_kg,
        circle_scrap_kg=circle_scrap_kg,
        per_model=per_model,
        narration_detail=narration_detail,
        skipped_missing_stock=sorted(skipped_missing, key=lambda e: e["model"]),
    )
